name: Deploy Hexo Blog to GitHub Pages

on:
  push:
    branches: [main]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - Check theme directory
        run: |
          echo "Checking theme directory structure..."
          ls -la themes/
          if [ -d "themes/cactus" ]; then
            echo "Cactus theme directory exists"
            ls -la themes/cactus/
            if [ -f "themes/cactus/_config.yml" ]; then
              echo "Theme config exists"
            else
              echo "Theme config missing"
            fi
          else
            echo "Cactus theme directory missing"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Debug - Check Hexo config
        run: |
          echo "Checking Hexo configuration..."
          cat _config.yml | grep -A 5 -B 5 "theme:"
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Hexo version:"
          npx hexo version

      - name: Clean and generate Hexo
        run: |
          npx hexo clean
          npx hexo list themes
          npx hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
